name: riverpod_swr
description: A lightweight SWR (Stale-While-Revalidate) utility for Riverpod.
publish_to: 'none'
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
