name: riverpod_swr
description: A robust SWR (Stale-While-Revalidate) data fetching library for Riverpod.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  async: ^2.12.0
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  meta: ^1.15.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0
  very_good_analysis: ^10.0.0
