name: narou_parser
description: なろう小説パーサー
version: 0.1.0

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  freezed_annotation:
  html:
  json_annotation:
  meta: ^1.12.0

dev_dependencies:
  build_runner:
  freezed:
  json_serializable: ^6.11.2
  test:
  very_good_analysis:
